### ISSUE TITLE
Deprecated hook "after:deploy:createDeploymentArtifacts" on Serverless 1.41.1

### ISSUE THREAD

**Issue by spam-man** [weixu365/serverless-scriptable-plugin#31]
Getting this warning on Serverless 1.41.1:

```
WARNING: Plugin Scriptable uses deprecated hook after:deploy:createDeploymentArtifacts,                      use package:createDeploymentArtifacts hook instead
```

(thanks for the great plugin!)

**Comment by weixu365** [comment]
That's because you are using the deprecated hook `after:deploy:createDeploymentArtifacts`, to fix this warning, just change the hook to `package:createDeploymentArtifacts`. 

The plugin doesn't use any hook by itself, all the settings are configured in the Serverless config file.

I will also change the readme to use the new hook name.

**Comment by weixu365** [comment]
Removed the deprecated hook in the readme.
